config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  resources :books do
    resources :comments, only:[:create, :edit, :update, :destroy], shallow: true
    resource :favorites, only:[:create, :destroy]
    resources :tags, only:[:show]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resource :follows, only: [:create, :destroy]
  get '/users', to: 'users#index', as: 'users_index'
  root "home#top"
  get '/home/about', to: 'home#about',as: 'about'
  get '/follows' => 'follows#index_follows', as: 'follow_list'
  get '/folloewrs' => 'follows#index_followers', as: 'follower_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows, dependent: :destroy
  validates :name,  length: { in: 2..20 }
  validates :introduction, length:{maximum: 50 }
  validates_uniqueness_of :name
  attachment :profile_image
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    flash[:notice] = 'Welcome! You have signed up successfully.'
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    flash[:notice] = 'Signed in successfully.'
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    flash[:notice] = 'Signed out successfully.'
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @post = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @post = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      flash[:notice] = 'User was successfully updated.'
      redirect_to user_path(@user.id)
    else
      flash[:error] = 'error.'
      redirect_to user_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # userのフォロワーをすべて格納する
  def follower_of(user)
    Follow.where(follower_id: user.id)
  end

  # userのフォローしているユーザーをすべて格納する
  def follow_user_of(user)
    Follow.where(follow_id: user.id)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h1>User info</h1>
      <%= form_for(@user) do |f| %>
        <label>Name
        <%= f.text_field :name %>
        </label>
        <p>image</p>
        <div class="user-edit-image">
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg"%>
        </div>
        <label class="control-label sr-only" for="inputEmail">ProfileImage</label>
        <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class: "user-edit-form" %>
        <label>Introduction
        <%= f.text_area :introduction %>
        </label>
        <%= f.submit %>
      <% end %>
    </div>    

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/userinfo' %>
    </div>    
    <div class="col-9">
      <h1>Users</h1>
      <table class="table">
        <th class="table_header">image</th>
        <th class="table_header">name</th>
        <th class="table_header"></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td class="table_data">
          <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
          <% end %>
          </td>
          <td class="table_data"><%= user.name %></td>
          <td class="table_data"><%= link_to 'show', user_path(user.id) %></td>
        </tr>
      <% end %>
    </table>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/newbook' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/userinfo' %>
    </div>    
    <div class="col-9">
      <h1>Books</h1>
      <table class="table">
      <tr>
        <th class="table_header"></th>
        <th class="table_header">Title</th>
        <th class="table_header">Opinion</th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <td>
          <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book), method: :delete, class:"btn btn-sm btn-danger" do %>
              ♡<%= book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book), method: :post, class:"btn btn-sm btn-outline-danger" do %>
              ♡<%= book.favorites.count %>
            <% end %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to book_path(book.id) do%>
            <%= book.title %>
          <% end %>
          </td>
          <td class="table_data"><%= book.body %></td>
        </tr>
      <% end %>
    </table>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/newbook' %>
    </div>
  </div>
</div>