config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  resources :books do
    resources :comments, only:[:create, :edit, :update, :destroy], shallow: true
    resource :favorites, only:[:create, :destroy]
    resources :tags, only:[:show]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resource :follows, only: [:create, :destroy]
  get '/users', to: 'users#index', as: 'users_index'
  root "home#top"
  get '/home/about', to: 'home#about',as: 'about'
  get '/follows' => 'follows#index_follows', as: 'follow_list'
  get '/folloewrs' => 'follows#index_followers', as: 'follower_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true
  validates :body,  length: { maximum: 200 }
  validates :title, :body, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :book
  has_many :descriptions, dependent: :destroy
  accepts_nested_attributes_for :descriptions, allow_destroy: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows, dependent: :destroy
  validates :name,  length: { in: 2..20 }
  validates :introduction, length:{maximum: 50 }
  validates_uniqueness_of :name
  attachment :profile_image
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def home
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @books = Book.all
    @post = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @post = Book.new
    @comment = Comment.new
    @comments = Comment.where(book_id: @book.id)
    @favos = Favorite.where(book_id: @book.id)
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.valid?
      book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(book.id)
    else
      flash[:error] = "error."
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.valid?
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      flash[:error] = 'error.'
      redirect_to book_path(@book.id)
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, tags_attributes: [:id, :name, 
      :_destroy, descriptions_attributes:[:id, :body]])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :correct_user, only: [:edit, :update, :destroy]
  def create
    @book = Book.find(params[:book_id])
    comment = Comment.new(comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    if comment.save
      flash[:notice] = 'comment was successfully created!'
      redirect_to @book
    else
      flash.new[:error] = 'comment error.'
      render @book
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    comment = Comment.find(params[:id])
    comment.update(comment_params)
    redirect_to book_path(comment.book_id)
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to book_path(comment.book_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def correct_user
    comment = Comment.find(params[:id])
    @user = comment.user
    redirect_to(root_url) unless current_user == @user
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new
    favorite.book_id = book.id
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
  def index_follows
    follow_id = params[:format].to_i
    follow = Follow.where(follow_id: follow_id)
    if !!follow
      @users=[]
      follow.each do |f|
        @users.push(User.find(f.follower_id))
      end
      render "follows/index"
    else
      flash[:error] = "This user don't follow any user."
      redirect_back(fallback_location: root_path)
    end
  end

  def index_followers
    follower_id = params[:format].to_i
    follow = Follow.find_by(follower_id: follower_id)
    if !!follow
      @users = User.where(id: follow.follow_id)
      render "follows/index"
    else
      flash[:error] = "This user don't have any follower."
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    follow = Follow.new(follower_id: params[:format], follow_id: current_user.id)
    follow.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    follow = Follow.where(follower_id: params[:format])
    follow = follow.find_by(follow_id: current_user.id)
    follow.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end
  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @post = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @post = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      flash[:notice] = 'User was successfully updated.'
      redirect_to user_path(@user.id)
    else
      flash[:error] = 'error.'
      redirect_to user_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # current_userがuserをフォローしているか
  def follow?(user)
    followers = Follow.where(follow_id: current_user.id)
    followers.where(follower_id: user.id).exists?
  end
end

app/helpers/books_helper.rb
module BooksHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # userのフォロワーをすべて格納する
  def follower_of(user)
    Follow.where(follower_id: user.id)
  end

  # userのフォローしているユーザーをすべて格納する
  def follow_user_of(user)
    Follow.where(follow_id: user.id)
  end
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <h1>Editing Book</h1>
    <div>
    <%= form_for(@book) do |f| %>
      <label class="d-block w-100">Title
      <%= f.text_field :title, class:"d-block w-100" %>
      </label>
      <label class="d-block w-100">Opinion
      <%= f.text_area :body, class:"d-block w-100" %>
      </label>
      <h4>タグ</h4>
      <div class="tags">
        <%= f.fields_for :tags do |tag| %>
          <%= render 'layouts/tag_fields', :f => tag %>
        <% end %>
        <%= link_to_add_association 'タグを追加', f, :tags,partial: 'layouts/tag_fields' %>
      </div>
      <%= f.submit class:"btn btn-primary btn-block"  %>
    <% end %>
    </div>
  <%= link_to "show", book_path(@book.id)%> | <%= link_to "Back", books_path %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/books/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-3"></div>
    <div class="col-6 mt-4">
      <h1>welcome to <i class="fas fa-book"></i>Bookers</h1>
      <p>In <i class="fas fa-book"></i><b>Bookers</b>,<br>
      you can share and exchange your opinions , inpressions , and emotions<br>
      about varioius books!</p>
      <%= link_to "sign in", new_user_session_path, class:"btn btn-primary btn-block" %>
      <%= link_to "sign up", new_user_registration_path, class:"btn btn-secondary btn-block "%>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/userinfo' %>
    </div>    
    <div class="col-9">
      <h1>Books</h1>
      <table class="table">
      <tr>
        <th class="table_header">いいね</th>
        <th class="table_header">投稿者</th>
        <th class="table_header">タイトル</th>
        <th class="table_header">感想</th>
      </tr>
      <% @books.each do |book| %>
        <tr>
          <td>
          <% if book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(book), method: :delete, class:"btn btn-sm btn-danger" do %>
              ♡<%= book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(book), method: :post, class:"btn btn-sm btn-outline-danger" do %>
              ♡<%= book.favorites.count %>
            <% end %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to user_path(book.user_id) do %>
            <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
            <%= book.user.name %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to book_path(book.id) do%>
            <%= book.title %>
          <% end %>
          </td>
          <td class="table_data"><%= book.body %></td>
        </tr>
      <% end %>
    </table>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/newbook' %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/userinfo' %>
    </div>    
    <div class="col-9">
      <h1>Book detail</h1>
      <table class="table">
        <tr>
          <td>
          <% if @book.favorited_by?(current_user) %>
            <%= link_to book_favorites_path(@book), method: :delete, class:"btn btn-sm btn-danger" do %>
              ♡<%= @book.favorites.count %>
            <% end %>
          <% else %>
            <%= link_to book_favorites_path(@book), method: :post, class:"btn btn-sm btn-outline-danger" do %>
              ♡<%= @book.favorites.count %>
            <% end %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to user_path(@book.user_id) do %>
            <%= attachment_image_tag @book.user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>    
            <%= @book.user.name %>
          <% end %>
          </td>
          <td class="table_data">
          <%= link_to book_path(@book.id) do%>
            <%= @book.title %>
          <% end %>
          </td>
          <td class="table_data"><%= @book.body %></td>
        <% if @book.user_id == current_user.id %>
          <td class="table_data"><%= link_to "Edit", edit_book_path(@book.id) %></td>
          <td class="table_data"><%= link_to "Delete", book_path(@book.id), method: :delete, data: {confirm:"本当に削除しますか"}%></td>
        <% end %>
        </tr>
      </table>
      <p>タグ：
      <% @book.tags.each do |tag| %>
        <%= link_to book_tag_path(@book,tag) do %>
          <span class="badge badge-secondary" ><%= tag.name %> </span>
        <% end %>
      <% end %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
    <%= render 'layouts/newbook' %>
    </div>
    <div class="col-6">
    <%= render 'layouts/favo_and_comments' %>
    </div>
    <div class="col-3">
    <%= render 'layouts/commentPost' %>
    </div>
  </div>
</div>


app/views/comments/edit.html.erb
<div class="container">
  <div class="row">
  <div class="col-3"></div>
  <div class="col-6">
    <h1>Editing comment</h1>
    <div>
    <%= form_for(@comment) do |f| %>
      <label class="d-block w-100">本文
      <%= f.text_area :body, class:"d-block w-100" %>
      </label>
      <%= f.submit class:"btn btn-primary btn-block"  %>
    <% end %>
    </div>
    <div class="col-3"></div>
  </div>
</div>

app/views/follows/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-2">
    </div>    
    <div class="col-10">
      <h1><%= yield :title %></h1>
      <table class="table">
      <tr>
        <th class="table_header">image</th>
        <th class="table_header">name</th>
        <th class="table_header"></th>
      </tr>
      <% @users.each do |user| %>
        <tr>
          <td class="table_data">
          <%= link_to user_path(user.id) do %>
            <%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg", size:'40x40' %>
          <% end %>
          </td>
          <td class="table_data"><%= user.name %></td>
          <td class="table_data"><%= link_to 'show', user_path(user.id) %></td>
        </tr>
      <% end %>
    </table>
    </div>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-9">
      <h2>タグの詳細</h2>
      <p>タグ名: <%= @tag.name%></p>
      <ul>
        <% @tag.descriptions.each do |desc| %>
          <li>
            <%= desc.body %>
          </li>
        <% end %>
      </ul>
      </p>
    </div>
  </div>
</div>