config/routes.rb
Rails.application.routes.draw do
  get 'tags/show'
  devise_for :users
  resources :books do
    resources :comments, only:[:create, :edit, :update, :destroy], shallow: true
    resource :favorites, only:[:create, :destroy]
    resources :tags, only:[:show]
  end
  resources :users, only: [:index, :show, :edit, :update]
  resource :follows, only: [:create, :destroy]
  get '/users', to: 'users#index', as: 'users_index'
  root "home#top"
  get '/home/about', to: 'home#about',as: 'about'
  get '/follows' => 'follows#index_follows', as: 'follow_list'
  get '/folloewrs' => 'follows#index_followers', as: 'follower_list'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy
  accepts_nested_attributes_for :tags, allow_destroy: true
  validates :body,  length: { maximum: 200 }
  validates :title, :body, presence: true
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/description.rb
class Description < ApplicationRecord
  belongs_to :tag
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :book
  has_many :descriptions, dependent: :destroy
  accepts_nested_attributes_for :descriptions, allow_destroy: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:name]
  has_many :books, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follows, dependent: :destroy
  validates :name,  length: { in: 2..20 }
  validates :introduction, length:{maximum: 50 }
  validates_uniqueness_of :name
  attachment :profile_image
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def home
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end

  def index
    @books = Book.all
    @post = Book.new
    @user = User.find(current_user.id)
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @post = Book.new
    @comment = Comment.new
    @comments = Comment.where(book_id: @book.id)
    @favos = Favorite.where(book_id: @book.id)
  end

  def create
    book = Book.new(book_params)
    book.user_id = current_user.id
    if book.valid?
      book.save
      flash[:notice] = 'Book was successfully created.'
      redirect_to book_path(book.id)
    else
      flash[:error] = "error."
      redirect_to books_path
    end
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user_id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    if @book.valid?
      flash[:notice] = 'Book was successfully updated.'
      redirect_to book_path(@book.id)
    else
      flash[:error] = 'error.'
      redirect_to book_path(@book.id)
    end
  end
  
  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, tags_attributes: [:id, :name, 
      :_destroy, descriptions_attributes:[:id, :body]])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    if user_signed_in?
      redirect_to user_path(current_user.id)
    end
  end
  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def show
    @tag = Tag.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @post = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @post = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.valid?
      flash[:notice] = 'User was successfully updated.'
      redirect_to user_path(@user.id)
    else
      flash[:error] = 'error.'
      redirect_to user_path(@user.id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # current_userがuserをフォローしているか
  def follow?(user)
    followers = Follow.where(follow_id: current_user.id)
    followers.where(follower_id: user.id).exists?
  end
end

app/helpers/books_helper.rb
module BooksHelper

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # userのフォロワーをすべて格納する
  def follower_of(user)
    Follow.where(follower_id: user.id)
  end

  # userのフォローしているユーザーをすべて格納する
  def follow_user_of(user)
    Follow.where(follow_id: user.id)
  end
end

app/views/layouts/_commentPost.html.erb
<%= form_for [@book,@comment] do |f| %>
  <p>コメント投稿</p>
  <%= f.text_area :body,size: "20x8" %><br>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/layouts/_description_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :body, value:"タグの説明" %>
    <%= f.text_area :body %>
  </div>
  <%= link_to_remove_association "説明を消す", f,class:"btn btn-outline-danger btn-sm" %>
  <hr>
</div>

app/views/layouts/_favo_and_comments.html.erb
<h3>コメント一覧</h3>
<ul>
<% @comments.each do |comment| %>
  <li>
    <%= comment.user.name %>さん：
    <%= comment.body %>
  <% if current_user == comment.user %>
    <%= link_to "edit", edit_comment_path(comment) %>
    | <%= link_to "delete", comment_path(comment), :method => :delete, data:{confirm: "本当にいいですか"} %>
  <% end %>
  </li>
<% end %>
</ul>
<h3>いいねしたユーザー</h3>
<ul>
<% @favos.each do |favo| %>
<li>
  <%= link_to user_path(favo.user) do %>
    <%= favo.user.name %>
  <% end %>
  さん
</li>
<% end %>
</ul>

app/views/layouts/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-10"></div>
      <div class="col-2">
      <footer>
        <p>CopyRight Infratop.inc</p>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand ml-5" href="/">Bookers</a>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navber" aria-controls="Navber" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="Navber">
    <ul class="navbar-nav">
      <li class="nav-item mr-5">
      <%= link_to root_path, class:"text-decoration-none text-light" do %>
        <i class="fas fa-home fa_white"></i><span> Home</span>
      <% end %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
        <%= link_to users_path, class:"text-decoration-none text-light" do %>
          <i class="fas fa-user fa_white"></i><span> Users</span>
        <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to books_path, class:"text-decoration-none text-light" do %>
          <i class="fas fa-book fa_white"></i><span> Books</span>
          <% end %>
        </li>
        <li class="nav-item mr-5">
        <%= link_to destroy_user_session_path, method: :delete, class:"text-decoration-none text-light" do %>
          <i class="fas fa-sign-out-alt fa_white"></i><span> Log out</span>
        <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
        <%= link_to  about_path, class:"text-decoration-none text-light" do %>
          <i class="fas fa-link fa_white"></i><span> About</span>
        <% end %>
        </li>
        <li class="nav-item mr-5">
        <%= link_to new_user_registration_path, class:"text-decoration-none text-light" do %>
          <i class="fas fa-user-plus fa_white"></i><span> Sign up</span>
        <% end %>
        </li>
        <li class="nav-item mr-5">
        <%= link_to new_user_session_path, class:"text-decoration-none text-light" do %>
          <i class="fas fa-sign-in-alt fa_white"></i><span> Log in</span>
        <% end %>
        </li>
      <% end %>

    </form>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_newbook.html.erb
<h1>New book</h1>
<%= form_for @post do |f| %>
  <p>Title</p>
  <%= f.text_field :title, class:"d-block w-100" %>
  <p>Body</p>
  <%= f.text_area :body, class:"d-block w-100" %>
  <h4>タグ</h4>
  <div class="tags">
    <%= f.fields_for :tags do |tag| %>
      <%= render 'layouts/tag_fields', :f => tag %>
    <% end %>
    <%= link_to_add_association 'タグを追加', f, :tags,partial: 'layouts/tag_fields' %>
  </div>
  <%= f.submit '保存',class:"btn btn-primary btn-block"%>
<% end %>

app/views/layouts/_notice.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:div, value, class: key) %>
<% end %>

app/views/layouts/_tag_fields.html.erb
<div class='nested-fields'>
  <div class="field">
    <%= f.label :name, value:"タグ名" %>
    <%= f.text_field :name %>
  </div>
  <div class="descriptions">
    <%= f.fields_for :descriptions do |desc| %>
      <%= render 'layouts/description_fields', :f => desc %>
    <% end %>
    <%= link_to_add_association '説明を追加', f, :descriptions,partial: 'layouts/description_fields' %>
  </div>
  <%= link_to_remove_association "タグを消す", f,class:"btn btn-outline-danger btn-sm" %>
  <hr>
</div>

app/views/layouts/_userinfo.html.erb

<h1>User info</h1>
<%= attachment_image_tag @user, :profile_image, :fill, 60, 60, format: 'jpeg', class: "img-circle pull-left profile-img", fallback: "no_image.jpg" %>
<hr>
<p>name:<%= @user.name %></p>
<hr>
<p>introduction:<%= @user.introduction %></p>
<%= link_to follow_list_path(@user) do%>
  <p>follows:<%= follow_user_of(@user).count %></p>
<% end %>
<%= link_to follower_list_path(@user) do%>
  <p>followers:<%= follower_of(@user).count %></p>
<% end %>
<% if @user.id == current_user.id %>
  <%= link_to edit_user_path(@user), class: "pull-right" do %>
  <span class="btn btn-light btn-block"><i class="fas fa-wrench"></i></span>
  <% end %>
<% else %>
  <% if follow?(@user) %>
    <%= link_to "followed", follows_path(@user), class:"btn btn-success btn-block", method: :delete %>
  <% else %>
    <%= link_to "follow", follows_path(@user), class:"btn btn-outline-success btn-block", method: :post %>
  <% end %>
<% end %>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/header' %>
  <% if flash[:notice] %>
    <p class="success_message"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:error] %>
    <p class="error_message"><%= flash[:error] %></p>
  <% end %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>